config/routes.rb
SPO::Application.routes.draw do

  root 'ui#view_home'

  get 'materials' => 'material#list', as: :material_list
  get 'material/create' => 'material#view_create', as: :material_view_create
  post 'material/create' => 'material#change', as: :material_create
  get 'material/:material_id' => 'material#get', as: :material_details
  post 'material/:id' => 'material#change', as: :material_change
  get 'material/:material_id/delete' => 'material#remove', as: :material_remove

  get 'quote/create' => 'quote#view_create', as: :quote_view_create
  post 'quote/create' => 'quote#create', as: :quote_create
  get 'quote/:access_id' => 'quote#get', as: :quote_details
  get 'quote/:access_id/order' => 'order#view_create', as: :order_view_create
  get 'quotes' => 'quote#list', as: :quote_list
  get 'quote' => 'quote#create', as: :quote_create_api

  post 'order' => 'order#create', as: :order_create
  get 'order/:access_id'  => 'order#get', as: :order_details
  get 'orders' => 'order#list', as: :order_list

  get 'customers' => 'customer#list', as: :customer_list
  get 'customer/create' => 'customer#view_create', as: :customer_view_create
  post 'customer/create' => 'customer#change', as: :customer_create
  get 'customer/:access_id' => 'customer#details', as: :customer_details
  get 'customer/:customer_access_id/plants' => 'customer#plants', as: :customer_plants

  get 'customer/:customer_access_id/plant' => 'plant#view_create', as: :plant_view_create
  post 'customer/:customer_access_id/plant' => 'plant#create', as: :plant_create
  get 'customer/:customer_access_id/plant/:plant_id' => 'plant#details', as: :plant_details
  delete 'customer/:customer_access_id/plant/:plant_id' => 'plant#remove', as: :plant_remove

  get 'history' => 'history#list', as: :history
  get 'statistics' => 'ui#statistics', as: :statistic
  get 'bender' => 'ui#bender', as: :bender

end

app/models/material.rb
class Material < ActiveRecord::Base
  has_many :stocks
  has_many :quotes
  has_many :volume_discounts

  # Validate presence of attributes
  validates_presence_of :short_name, :price, :replacement_time, :delivery_time, :production_cost, :minimal_price, :items_per_package

  def serializable_hash
    super(:only => [:id, :short_name, :long_name, :delivery_time, :updated_at]).merge(:current_stock => stock)
  end

  def stock
    stock_at Time.now.to_date
  end

  # Calculate the suggested stock based on the last 10 and next 30 days
  def suggested_stock
    quantity_transactions = []
    (-10..30).to_a.each do |i|
      day = Time.now.to_date + i.days
      stocks.where(:date => day, :direction => -1).each {|stock| quantity_transactions << stock.quantity}
    end
    if quantity_transactions.length > 0
      quantity_average = (quantity_transactions.inject{|sum, element| sum+element}.to_f/quantity_transactions.length).ceil
    else
      quantity_average = 0
    end

    quantity_average
  end

  def discount_for_quantity(quantity)
    discount = volume_discounts.where(['quantity <= ?', quantity]).order('quantity DESC').first
    return 1.0 if discount.nil?

    (1.0-(discount.discount.to_f/100)).to_i
  end

  # @param date [Date]
  def stock_at (date)
    return $redis.get("Simulation:StockAt:#{self[:id]}:#{date}").to_i if $redis.exists "Simulation:StockAt:#{self[:id]}:#{date}"

    stock = 0

    # Check if data set exists for yesterday in redis
    yesterday = Time.now.to_date-1.day
    if $redis.exists("Simulation:StockAt:#{self[:id]}:#{yesterday}")
      # Start from yesterday, reference to the future
      stock = $redis.get("Simulation:StockAt:#{self[:id]}:#{yesterday}").to_i
      stocks.where('date <= ?', date).where('date > ?', yesterday).each do |transaction|
        stock += transaction.volume
      end
    else
      stocks.where('date <= ?', date).each do |transaction|
        stock += transaction.volume
      end
    end

    # Cache in redis
    $redis.set("Simulation:StockAt:#{self[:id]}:#{date}", stock)
    if date >= Time.now.to_date
      # Expire after 10 minutes if today or future date
      $redis.expire("Simulation:StockAt:#{self[:id]}:#{date}", 10.minutes)
    end

    stock
  end

  def replacement_orders_at (date)
    stock = 0
    ReplacementOrder.where(:material_id => self[:id], :order_date => date).each do |order|
      stock += order.quantity
    end

    stock
  end

  def outgoing_deliveries_at (date)
    stock = 0
    Stock.where(:material_id => self[:id], :direction => 1, :date => date).each do |delivery|
      stock += delivery.quantity
    end

    stock
  end

  def incoming_deliveries_at (date)
    stock = 0
    Stock.where(:material_id => self[:id], :direction => -1, :date => date).each do |delivery|
      stock += delivery.quantity
    end

    stock
  end

  def reduce_stock_at (date, by, reference='')
    stock = stocks.create(:direction => -1, :quantity => by, :change_ref => reference, :date => date)

    return nil unless stock.save

    stocks
  end

  def increase_stock_at (date, by, reference='')
    # Cancel if in replacement_time
    return nil if date-(self[:replacement_time]+1).days < Time.now.to_date

    stock = stocks.create(:direction => 1, :quantity => by, :change_ref => reference, :date => date)

    return nil unless stock.save

    stocks
  end

  def in_replacement_time? (date)
    Time.now.to_date >= date-(self[:replacement_time]+1).days
  end

  # @return Quote
  def add_quote
    quote = quotes.create(:valid_till => Time.now.to_datetime+$quote_lifetime, :active_quote => true)
    o = [('a'..'z'), ('A'..'Z'), (0..9)].map { |i| i.to_a }.flatten
    quote.access_id = (0...4).map{ o[rand(o.length)] }.join

    return nil unless quote.save

    quote
  end

  def check_availability (quantity, target_date)
    # Check if target_date is outside the replacement_time
    return true if target_date > (Time.now.to_date+(self[:replacement_time]+1).days)

    # Fetch available stock between target_date and replacement_time
    stock_availability = (0..((Time.now.to_date+(self[:replacement_time]+1).days)-target_date).to_i).map{|el| date = target_date+el.days; stock_at(date)}

    # Reduce the stock by quantity, check if array includes negative values -> if yes, requested quantity is not available
    stock_availability.map{|stock_at_day| stock_at_day-quantity}.reject { |element| element < 0 }.length == stock_availability.length
  end

  def self.get(id)
    Material.where(:id => id, :active => true).first
  end
end

app/controllers/material_controller.rb
class MaterialController < ApplicationController
  def list
    materials = Material.where(:active => true)
    @materials = materials
    respond_to do |f|
      f.html
      f.json { render :json => materials.map { |material| {:id => material.id, :details_url => material_details_url(:material_id => material.id, :format => :json)}} }
    end
  end

  # :material_id
  def get
    @material = Material.get params[:material_id]
    error! 'Material not found', :error_code => 404 if @material.nil?

    @material_stock = (0..10).to_a.map{|i| day = Time.now.to_date + i.days; {:day => day.to_s, :ordered_incoming => @material.replacement_orders_at(day), :deliveries_at => @material.outgoing_deliveries_at(day), :deliveries_incoming => @material.incoming_deliveries_at(day)}}

    @stock_over_time = (-5..10).to_a.map do |i|
      day = Time.now.to_date + i.days
      {:day => day, :stock => @material.stock_at(day)}
    end

    respond_to do |f|
      f.json { render :json => @material.serializable_hash }
      f.html
    end
  end

  def view_create
    respond_to do |f|
      f.html
    end
  end

  # :id
  def change
    if params.has_key? :id
      material = Material.find_by_id params[:id]
      error! 'Material not found', :error_code => 404 if material.nil?
    else
      material = Material.new
    end

    params.each do |key, value|
      next unless material.has_attribute? key
      next if key == :id

      material[key] = value
    end

    material.save!
    HistoryEntry.create :message => "Material ##{material.id} created", :type => 'fa-cubes', :url => material_details_path(:material_id => material.id)

    redirect_to material_details_path(:material_id => material.id)
  end

  # :material_id
  def remove
    material = Material.get params[:material_id]
    error! 'Material not found', :error_code => 404 if material.nil?

    material.active = false
    material.save

    HistoryEntry.create :message => "Material ##{material.id} deactivated", :type => 'fa-cubes'

    redirect_to material_list_path(:message => "Material #{material.id} has been deactivated")
  end
end

app/helpers/material_helper.rb
module MaterialHelper
end

app/views/material/get.html.erb
<% content_for :title do %>Material #<%=@material.id%><% end %>
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Material</h1>
  </div>
</div>
<div class="row">
    <div class="col-lg-6">
      <table class="table table-responsive">
        <tr>
          <td class="lead no-border">ID</td>
          <td class="no-border"><%=@material.id%></td>
        </tr>
        <tr>
          <td class="lead no-border">Short name</td>
          <td class="no-border"><%=@material.short_name%></td>
        </tr>
        <tr>
          <td class="lead">Long name</td>
          <td><%=@material.long_name%></td>
        </tr>
        <tr>
          <td class="lead">Price</td>
          <td><%=number_to_currency(@material.price.to_f/100, unit: '€', separator: ',', delimiter: '.', format: '%n %u')%></td>
        </tr>
        <tr>
          <td class="lead">Delivery Time</td>
          <td><%=@material.delivery_time%></td>
        </tr>
        <tr>
          <td class="lead">Replacement Time</td>
          <td><%=@material.replacement_time%></td>
        </tr>
        <tr>
          <td class="lead">Production Cost</td>
          <td><%=number_to_currency(@material.production_cost.to_f/100, unit: '€', separator: ',', delimiter: '.', format: '%n %u')%></td>
        </tr>
        <tr>
          <td class="lead">Minimal Price</td>
          <td><%=number_to_currency(@material.minimal_price.to_f/100, unit: '€', separator: ',', delimiter: '.', format: '%n %u')%></td>
        </tr>
        <tr>
          <td class="lead">Items per Package</td>
          <td><%=@material.items_per_package%></td>
        </tr>


        <tr>
          <td class="lead">Currently in stock</td>
          <td><%=@material.stock%></td>
        </tr>

        <tr>
          <td class="lead">Suggested Stock</td>
          <td><%=@material.suggested_stock%></td>
        </tr>
      </table>
    </div>
  <div class="col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        Stock Transactions
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body" id="chart-base" style="height:250px;">
      </div>
      <!-- /.panel-body -->
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        Stock over Time
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body" id="chart-time" style="height:250px;">
      </div>
      <!-- /.panel-body -->
    </div>
  </div>

</div>


<% content_for :foot do %>
    <script type="text/javascript">
        $(document).ready(function() {
            var analyze_information = jQuery.parseJSON('<%= raw @material_stock.to_json%>');
            new Morris.Bar({
                element: 'chart-base',
                data: analyze_information,
                xkey: 'day',
                ykeys: ['ordered_incoming', 'deliveries_at', 'deliveries_incoming'],
                labels: ['Replacement Orders', 'Order Deliveries', 'Replacement Deliveries'],
                barColors: ['#428bca', '#F14B51', '#2a6496']
            });

            var stock_over_time = jQuery.parseJSON('<%= raw @stock_over_time.to_json%>');
            new Morris.Line({
                element: 'chart-time',
                data: stock_over_time,
                xkey: 'day',
                ykeys: ['stock'],
                labels: ['Stock'],
                lineColors: ['#428bca'],
                smooth: false
            });
        });
    </script>
<% end %>

app/views/material/list.html.erb
<% content_for :title do %>Material<% end %>
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Material <a href="<%= material_view_create_path %>" class="btn pull-right btn-success"><span class="fa fa-plus"></span> Create</a></h1>
  </div>
</div>
<div class="row">
<div class="col-lg-12">
  <p>We have <strong><%=@materials.length %></strong> different materials.</p>
  <div class="table-responsive">
  <table class="table table-stripped table-hover sortable">
    <thead>
    <tr>
      <th>#</th>
      <th>Name <span class="fa fa-sort pull-right sort"></span></th>
      <th>Longname <span class="fa fa-sort pull-right sort"></span></th>
      <th>Price <span class="fa fa-sort pull-right sort"></span></th>
      <th>Delivery time <span class="fa fa-sort pull-right sort"></span></th>
      <th>Current stock <span class="fa fa-sort pull-right sort"></span></th>
      <th> </th>
      <th> </th>
    </tr>
    </thead>
    <tbody>
    <% @materials.each do |material| %>
        <tr>
          <td><%= material.id %></td>
          <td><a href="<%= material_details_path(:material_id => material.id)%>"><strong><%= material.short_name%></strong></a></td>
          <td><%= material.long_name%></td>
          <td><%=number_to_currency(material.price.to_f/100, unit: '€', separator: ',', delimiter: '.', format: '%n %u')%></td>
          <td><%= material.delivery_time %></td>
          <td><%= material.stock %></td>
          <td>
            <a href="<%= material_details_path(:material_id => material.id)%>"><span class="fa fa-long-arrow-up"></span> View details</a>
          </td>
          <td>
            <a class="label label-danger pull-right delete" href="<%=material_remove_path(:material_id => material.id)%>"><span class="fa fa-times"></span> </a>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
    </div>
 </div>
</div>

app/views/material/view_create.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Create Material</h1>
  </div>
</div>
<div class="row">
  <div class="col-lg-8">
    <form action="<%=material_create_path%>" method="post">

      <!-- Table -->
      <table class="table">
        <tr>
          <td class="lead no-border">Short name</td>
          <td class="no-border"><input type="text" class="form-control" name="short_name"></td>
        </tr>
        <tr>
          <td class="lead">Long name</td>
          <td><input type="text" class="form-control" name="long_name"></td>
        </tr>
        <tr>
          <td class="lead">Price</td>
          <td><input type="number" class="form-control" name="price"></td>
        </tr>
        <tr>
          <td class="lead">Delivery Time</td>
          <td><input type="number" class="form-control" name="delivery_time"></td>
        </tr>
        <tr>
          <td class="lead">Replacement Time</td>
          <td><input type="number" class="form-control" name="replacement_time"></td>
        </tr>
        <tr>
          <td class="lead">Production Cost</td>
          <td><input type="number" class="form-control" name="production_cost"></td>
        </tr>
        <tr>
          <td class="lead">Minimal Price</td>
          <td><input type="number" class="form-control" name="minimal_price"></td>
        </tr>
        <tr>
          <td class="lead">Items per Package</td>
          <td><input type="number" class="form-control" name="items_per_package"></td>
        </tr>
        <tr>
          <td></td>
          <td><input type="submit" class="btn btn-success" value="Submit"></td>
        </tr>

      </table>

    </form>
  </div>
</div>