config/routes.rb
SPO::Application.routes.draw do

  root 'ui#view_home'

  get 'materials' => 'material#list', as: :material_list
  get 'material/create' => 'material#view_create', as: :material_view_create
  post 'material/create' => 'material#change', as: :material_create
  get 'material/:material_id' => 'material#get', as: :material_details
  post 'material/:id' => 'material#change', as: :material_change
  get 'material/:material_id/delete' => 'material#remove', as: :material_remove

  get 'quote/create' => 'quote#view_create', as: :quote_view_create
  post 'quote/create' => 'quote#create', as: :quote_create
  get 'quote/:access_id' => 'quote#get', as: :quote_details
  get 'quote/:access_id/order' => 'order#view_create', as: :order_view_create
  get 'quotes' => 'quote#list', as: :quote_list
  get 'quote' => 'quote#create', as: :quote_create_api

  post 'order' => 'order#create', as: :order_create
  get 'order/:access_id'  => 'order#get', as: :order_details
  get 'orders' => 'order#list', as: :order_list

  get 'customers' => 'customer#list', as: :customer_list
  get 'customer/create' => 'customer#view_create', as: :customer_view_create
  post 'customer/create' => 'customer#change', as: :customer_create
  get 'customer/:access_id' => 'customer#details', as: :customer_details
  get 'customer/:customer_access_id/plants' => 'customer#plants', as: :customer_plants

  get 'customer/:customer_access_id/plant' => 'plant#view_create', as: :plant_view_create
  post 'customer/:customer_access_id/plant' => 'plant#create', as: :plant_create
  get 'customer/:customer_access_id/plant/:plant_id' => 'plant#details', as: :plant_details
  delete 'customer/:customer_access_id/plant/:plant_id' => 'plant#remove', as: :plant_remove

  get 'history' => 'history#list', as: :history
  get 'statistics' => 'ui#statistics', as: :statistic
  get 'bender' => 'ui#bender', as: :bender

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :material
  belongs_to :customer
  has_one :order
  belongs_to :plant
  has_many :deliveries

  def serializable_hash
    x = super(:only => [:id, :access_id, :call_id, :valid_till])
    if plant.nil?
      x.merge!(:distance => nil)
    else
      x.merge!(:distance => plant.distance)
    end
    x.merge!(:quantity => quantity, :price => price, :logistic_cost => logistic_cost, :total => total_price, :deliveries => deliveries.map {|delivery| delivery.serializable_hash})

    # Map alternatives
    alt_quotes = alternatives
    x.merge!(:alternatives => alt_quotes.map{|alternative| alternative.serializable_hash}) if alt_quotes.length > 0

    x
  end

  def has_order?
    !order.nil?
  end

  def price
    price = 0
    deliveries.each {|delivery| price += delivery.price}

    price
  end

  def active?
    return false unless active_quote?
    return parent_quote.active? unless parent_quote.nil?

    self[:valid_till] > Time.now.to_datetime
  end

  def calculate_quantity!
    quantity = 0
    deliveries.each {|delivery| quantity += delivery.quantity}

    self[:quantity] = quantity
  end

  def block_material!
    if parent_quote.nil?
      delivery_dates = {}
      (alternatives+[self]).each do |quote|
        quote.deliveries.each do |delivery|
          if delivery_dates.has_key? delivery.date.to_s
            delivery_dates[delivery.date.to_s] = delivery.quantity if delivery.quantity > delivery_dates[delivery.date.to_s]
          else
            delivery_dates[delivery.date.to_s] = delivery.quantity
          end
        end
      end

      delivery_dates.each do |date, quantity|
        material.stocks.create(:direction => -1, :quantity => quantity, :change_ref => "quote:#{self[:id]}", :date => Date.parse(date))

        HistoryEntry.create(:message => "#{quantity} units of Material #{material.id} blocked for quote ##{self[:id]} at #{date}", :type => 'fa-thumb-tack')
      end
    else
      parent_quote.block_material!
    end
  end

  def free_material!
    if parent_quote.nil?
      Stock.where(:change_ref => "quote:#{self[:id]}").destroy_all
      (alternatives+[self]).each{|quote| quote.active_quote = false; quote.save}

      HistoryEntry.create(:message => "Blocked Stock for Quote ##{self[:id]} has been released.", :type => 'fa-check-square')
    else
      parent_quote.free_material!
    end
  end

  def logistic_cost
    costs = 0
    deliveries.each {|delivery| costs += delivery.logistic_cost}

    costs
  end

  def total_price
    price+logistic_cost
  end

  def alternatives
    Quote.find_by_sql(['SELECT quotes.* FROM quote_alternatives, quotes WHERE quote_alternatives.quote_id = ? AND quotes.id = quote_alternatives.alternative_id', self[:id]])
  end

  def parent_quote
    Quote.find_by_sql(['SELECT quotes.* FROM quote_alternatives, quotes WHERE quote_alternatives.alternative_id = ? AND quotes.id = quote_alternatives.quote_id', self[:id]]).first
  end

  def add_alternative
    quote = Quote.create(:date => self[:date], :quantity => self[:quantity], :material_id => self[:material_id], :active_quote => true)
    o = [('a'..'z'), ('A'..'Z'), (0..9)].map { |i| i.to_a }.flatten
    quote.access_id = (0...4).map{ o[rand(o.length)] }.join

    quote.save
    QuoteAlternative.create(:quote => self, :alternative => quote).save

    quote
  end

  def add_delivery(options={})
    options.merge!(:quote_id => self[:id])

    delivery = Delivery.create options
    delivery.calculate_logistic_cost!
    delivery.calculate_price!

    delivery
  end

  def add_order(external_id, quantity)
    puts 1
    return nil if has_order?
    puts 2
    return nil unless active?
    puts 3

    free_material!

    new_order = Order.create(:quantity => quantity, :external_id => external_id, :quote_id => self[:id])
    o = [('a'..'z'), ('A'..'Z'), (0..9)].map { |i| i.to_a }.flatten
    new_order.access_id = (0...4).map{ o[rand(o.length)] }.join

    return nil unless new_order.save

    if quantity == self[:quantity]
      deliveries.each do |delivery|
        delivery.replace_material!
        material.reduce_stock_at(delivery.date, delivery.quantity, "order:#{self[:id]}")
        HistoryEntry.create(:message => "New Delivery for Order ##{new_order.id} scheduled", :type => 'fa-truck')
      end
    else
      # Check out and replace materials
      shipped_units = 0

      # For each planned delivery, checkout and replace materials while quantity does not extend ordered quantity
      deliveries.each do |delivery|
        if shipped_units < quantity
          mx = shipped_units+delivery.quantity
          if mx > quantity
            delivery.quantity = delivery.quantity-(mx-quantity)
            delivery.save
          end

          delivery.replace_material!
          material.reduce_stock_at(delivery.date, delivery.quantity, "order:#{self[:id]}")
          shipped_units += delivery.quantity

          HistoryEntry.create(:message => "New Delivery for Order ##{new_order.id} scheduled", :type => 'fa-truck')
        else
          delivery.destroy
        end
      end
    end

    new_order
  end
end

app/controllers/quote_controller.rb
class QuoteController < ApplicationController
  # :material_id, :date (yyyymmdd), :call_id, :quantity, (:customer, :plant)
  def create
    error! 'Wrong input', :error_code => 400 unless params.has_key?(:material_id) && params.has_key?(:date) && params.has_key?(:call_id) && params.has_key?(:quantity)
    begin
      date = Date.strptime(params[:date].gsub('-', ''), '%Y%m%d')
    rescue
      error! 'Wrong date format', :error_code => 400
    end

    error! 'Date must be in future', :error_code => 400 unless date > Time.now.to_date

    existing_quote = Quote.where(:material_id => params[:material_id], :date => date, :call_id => params[:call_id].to_i, :requested_quantity => params[:quantity].to_i).first

    if existing_quote.nil?
      # Create new Quote (HTTP 201 [Created])
      # Fetch requested material
      material = Material.get params[:material_id]
      error! 'Material not found', :error_code => 404 if material.nil?

      # Check if delivery date is acceptable based on delivery time
      error! 'Delivery date not possible due to shipping time', :error_code => 400 unless date > Time.now.to_date+(material.delivery_time+1).day


      # Fetch customer and plant if given
      if params.has_key?(:customer) && params.has_key?(:plant) && params[:customer] != ''
        customer = Customer.find_by_access_id params[:customer]
        error! 'Customer not found', :error_code => 400 if customer.nil?

        plant = customer.customer_plants.where(:id => params[:plant]).first
        error! 'Plant not found', :error_code => 400 if plant.nil?
      end

      # Set requested quantity
      requested_quantity = params[:quantity].to_i

      # Create primary quote object
      quote = material.add_quote
      error! 'Unable to create quote' if quote.nil?

      quote.date = date
      quote.call_id = params[:call_id].to_i
      quote.requested_quantity = requested_quantity
      unless plant.nil?
        quote.customer_id = customer.id
        quote.plant_id = plant.id
      end
      error! 'Unable to create quote' unless quote.save

      # Primary quote only includes stock available at requested date.
      # Check if requested date is in replacement time -> check for availability needed
      if material.in_replacement_time?(date)

        # get stock at requested date
        stock_at_date = material.stock_at(date)

        # if stock_at_date is larger than or equal requested stock, only create primary quote
        if stock_at_date >= requested_quantity
          quote.add_delivery(:date => date, :quantity => requested_quantity, :material => material).save
        else
          # Primary quote will only include stock available at giving time spot
          quote.add_delivery(:date => date, :quantity => stock_at_date, :material => material).save

          # Add alternative quotes
          # Alternative 1: split delivery, unless first delivery quantity > 0
          if stock_at_date > 0
            alternative_quote = quote.add_alternative
            unless plant.nil?
              alternative_quote.customer_id = customer.id
              alternative_quote.plant_id = plant.id
              alternative_quote.save
            end

            # First delivery includes all stock available at requested time point
            alternative_quote.add_delivery(:date => date, :quantity => stock_at_date, :material => material).save

            # Create additional deliveries till stock is complete
            delivered_units = stock_at_date
            target_date = date.clone
            latest_added = date.clone

            while delivered_units < requested_quantity
              next_delivering_units = 0

              # Bundle availability in the next 14 days
              14.times do
                target_date = target_date+1.day

                # check if outside replacement time
                if material.in_replacement_time?(target_date)
                  available_stock = material.stock_at(target_date)
                else
                  available_stock = requested_quantity
                end

                if available_stock > next_delivering_units
                  next_delivering_units = available_stock-delivered_units
                  latest_added = target_date.clone

                  if next_delivering_units >= (requested_quantity-delivered_units)
                    next_delivering_units = (requested_quantity-delivered_units)
                    break
                  end
                end
              end

              # Add new delivery, if next_delivering_units > 0
              next unless next_delivering_units > 0
              alternative_quote.add_delivery(:date => latest_added, :quantity => next_delivering_units, :material => material).save
              delivered_units = delivered_units+next_delivering_units
            end

            # Save alternative quote
            alternative_quote.calculate_quantity!
            alternative_quote.save
          end


          # Second alternative: move delivery to later time point with complete requested units
          # Condition: next 30 days
          target_date = date.clone

          30.times do
            target_date = target_date+1.day

            # check if outside replacement time
            if material.in_replacement_time?(target_date)
              available_stock = material.stock_at(target_date)
            else
              available_stock = requested_quantity
            end

            # if available_stock > requested, exit loop, create delivery
            if available_stock >= requested_quantity

              # Add alternative quote
              alternative_quote = quote.add_alternative
              unless plant.nil?
                alternative_quote.customer_id = customer.id
                alternative_quote.plant_id = plant.id
                alternative_quote.save
              end

              alternative_quote.add_delivery(:date => target_date, :quantity => requested_quantity, :material => material).save
              alternative_quote.calculate_quantity!
              alternative_quote.save
              break
            end
          end
        end
      else
        # If not in replacement time, entire stock is available
        quote.add_delivery(:date => date, :quantity => requested_quantity, :material => material).save
      end

      quote.calculate_quantity!
      quote.block_material!
      quote.save

      HistoryEntry.create :message => "New quote added for material ##{quote.material_id}", :type => 'fa-asterisk', :url => quote_details_path(:access_id => quote.access_id)

      response['Location'] = quote_details_url(:access_id => quote.access_id, :format => :json)
      respond_to do |f|
        f.json { render :json => quote.serializable_hash, status: 201}
        f.html { redirect_to quote_list_path }
      end
    else
      # Angebot ausgeben (Status 303: See other)
      response['Location'] = quote_details_url(:access_id => existing_quote.access_id, :format => :json)
      respond_to do |f|
        f.json { render :json => existing_quote.serializable_hash, status: 303}
        f.html { redirect_to quote_list_path }
      end
    end
  end

  def get
    @quote = Quote.find_by_access_id params[:access_id]

    error! 'Quote not found', :error_code => 404 if @quote.nil?

    respond_to do |f|
      f.json { render :json => @quote.serializable_hash}
      f.html
    end
  end

  def view_create
    respond_to do |f|
      f.html
    end
  end

  def list
    @quotes = Quote.where('valid_till IS NOT NULL')
    respond_to do |f|
      f.html
    end
  end
end

app/helpers/quote_helper.rb
module QuoteHelper
end

app/views/quote/get.html.erb
<% content_for :title do %>Quote #<%=@quote.id%><% end %>
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Quote</h1>
  </div>
</div>
<% ([@quote]+(@quote.alternatives)).each do |quote| %>
    <div class="row">
      <div class="col-lg-12">
        <h2><%=quote == @quote ? 'Quote' : 'Alternative' %><%if quote.active?%><a href="<%= order_view_create_path(:access_id => quote.access_id) %>" class="btn pull-right btn-success"><span class="fa fa-plus"></span> Order</a><%end%></h2>
      </div>
      <div class="col-lg-12">
        <table class="table table-responsive">
          <tr>
            <td class="lead no-border">ID</td>
            <td class="no-border"><%= quote.id %></td>
          </tr>
          <tr>
            <td class="lead no-border">Status</td>
            <td class="no-border">
              <% if quote.has_order? %>
                  <span class="label label-success"><span class="fa fa-check"></span> Ordered</span>
              <% elsif quote.active? %>
                  <span class="label label-default"><span class="fa fa-circle"></span> Active</span>
              <% else %>
                  <span class="label label-danger"><span class="fa fa-clock-o"></span> Outdated</span>
              <% end %>
            </td>
          </tr>
          <tr>
            <td class="lead">Material</td>
            <td><%= quote.material.short_name %></td>
          </tr>
          <tr>
            <td class="lead">Quantity</td>
            <td><%= quote.quantity %></td>
          </tr>
          <tr>
            <td class="lead">Delivery Date</td>
            <td><%= quote.date %></td>
          </tr>
          <tr>
            <td class="lead">Price</td>
            <td><%= number_to_currency(quote.price.to_f/100, unit: '€', separator: ',', delimiter: '.', format: '%n %u') %></td>
          </tr>
          <tr>
            <td class="lead">Logistic Cost</td>
            <td><%= number_to_currency(quote.logistic_cost.to_f/100, unit: '€', separator: ',', delimiter: '.', format: '%n %u') %></td>
          </tr>
          <tr>
            <td class="lead">Price Total</td>
            <td><%= number_to_currency(quote.total_price.to_f/100, unit: '€', separator: ',', delimiter: '.', format: '%n %u') %></td>
          </tr>
          <tr>
            <td class="lead">Distance</td>
            <td><%= quote.plant.nil? ? 0 : number_with_delimiter((quote.plant.distance.to_f/1000).to_i, delimiter: '.', separator: ',') %>
              km
            </td>
          </tr>
        </table>
      </div>
    </div>
      <div class="row">
        <div class="col-lg-12">
          <h3>Deliveries</h3>
        </div>
        <% quote.deliveries.each_with_index do |delivery, i| %>
            <div class="col-lg-6">
              <div class="panel panel-default">
                <div class="panel-heading">
                  Delivery <%= i+1 %>
                </div>
                <div class="panel-body">
                  <table class="table table-responsive">
                    <tr>
                      <td>Quantity</td>
                      <td><%= delivery.quantity %></td>
                    </tr>
                    <tr>
                      <td>Shipping Date</td>
                      <td><%= delivery.shipping_date %></td>
                    </tr>
                    <tr>
                      <td>Delivery Date</td>
                      <td><%= delivery.delivery_date %></td>
                    </tr>
                    <tr>
                      <td>Price</td>
                      <td><%= number_to_currency(delivery.price.to_f/100, unit: '€', separator: ',', delimiter: '.', format: '%n %u') %></td>
                    </tr>
                    <tr>
                      <td>Logistic Cost</td>
                      <td><%= number_to_currency(delivery.logistic_cost.to_f/100, unit: '€', separator: ',', delimiter: '.', format: '%n %u') %></td>
                    </tr>
                  </table>
                </div>
              </div>
            </div>
        <% end %>
      </div>
<% end %>

app/views/quote/list.html.erb
<% content_for :title do %>Quotes<% end %>
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Quotes <a href="<%= quote_view_create_path %>" class="btn pull-right btn-success"><span class="fa fa-plus"></span> Create</a></h1>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <p>Currently <strong><%=@quotes.count %></strong> quotes where <%=Quote.where('valid_till IS NOT NULL').where(:active_quote => true).count%> are still open.</p>
    <div class="table-responsive">
      <table class="table table-stripped sortable table-hover">
        <thead>
        <tr>
          <th>#</th>
          <th>Status</th>
          <th>Material <span class="fa fa-sort pull-right sort"></span></th>
          <th>Date <span class="fa fa-sort pull-right sort"></span></th>
          <th>Quote </th>
        </tr>
        </thead>
        <tbody>
        <% @quotes.reverse.each do |quote| %>
            <tr>
              <td><%= quote.id %></td>
              <td><%if quote.has_order?%>
                    <span class="label label-success"><span class="fa fa-check"></span> Ordered</span>
                <%elsif quote.active?%>
                    <span class="label label-default"><span class="fa fa-circle"></span> Active</span>
                <%else%>
                    <span class="label label-danger"><span class="fa fa-clock-o"></span> Outdated</span>
                <%end%>
              </td>
              <td><a href="<%= material_details_path(:material_id => quote.material.id)%>"><%= quote.material.short_name %></a></td>
              <td><%= quote.date%></td>
              <td><a href="<%= quote_details_path(:access_id => quote.access_id)%>"><span class="fa fa-reply"></span> Show details</a></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/quote/view_create.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Create Quote</h1>
  </div>
</div>
<div class="row">
  <div class="col-lg-8">
    <form action="<%= quote_create_path %>" method="post">

      <!-- Table -->
      <table class="table">
        <tr>
          <td class="lead no-border">Material*</td>
          <td class="no-border">
            <select class="select2" name="material_id">
            <%Material.where(:active => true).each do |material|%>
                <option value="<%= material.id %>"><%= material.short_name %></option>
            <%end%>
          </select>
          </td>
        </tr>
        <tr>
          <td class="lead">Date</td>
          <td><input type="date" class="form-control" name="date"></td>
        </tr>
        <tr>
          <td class="lead">Call ID</td>
          <td><input type="number" class="form-control" name="call_id"></td>
        </tr>
        <tr>
          <td class="lead">Quantitiy</td>
          <td><input type="number" class="form-control" name="quantity"></td>
        </tr>
        <tr>
          <td class="lead">Customer</td>
          <td>
            <select class="select2" name="customer" id="customer-select">
            <option value=""></option>
          <%Customer.all.each do |customer|%>
              <option value="<%= customer.access_id %>" data-access-id="<%= customer.access_id %>"><%= customer.name %></option>
          <%end%>
            </select>
          </td>
        </tr>
        <tr>
          <td class="lead">Plant</td>
          <td><select class="select2" name="plant" id="plant-select">

            <option value=""></option>
          </select></td>
        </tr>
        <tr>
          <td></td>
          <td><input type="submit" class="btn btn-success" value="Submit"></td>
        </tr>

      </table>

    </form>
  </div>
</div>
<% content_for :foot do %>
<script type="text/javascript">
    $(document).ready(function () {
        $('#customer-select').change(function() {
            $("#plant-select").html('');
            var selectedOption = $(this).find(":selected");
            $.getJSON('/customer/'+selectedOption.attr('data-access-id')+'/plants.json', function (data) {
                console.log(data);
                for (var i = 0; i < data.length; i++) {
                    element = data[i];
                    $("#plant-select").append("<option value='"+element['id']+"'>"+element['address']+"</option>");
                }

            });
        });
    })
</script>
<% end %>