config/routes.rb
SPO::Application.routes.draw do

  root 'ui#view_home'

  get 'materials' => 'material#list', as: :material_list
  get 'material/create' => 'material#view_create', as: :material_view_create
  post 'material/create' => 'material#change', as: :material_create
  get 'material/:material_id' => 'material#get', as: :material_details
  post 'material/:id' => 'material#change', as: :material_change
  get 'material/:material_id/delete' => 'material#remove', as: :material_remove

  get 'quote/create' => 'quote#view_create', as: :quote_view_create
  post 'quote/create' => 'quote#create', as: :quote_create
  get 'quote/:access_id' => 'quote#get', as: :quote_details
  get 'quote/:access_id/order' => 'order#view_create', as: :order_view_create
  get 'quotes' => 'quote#list', as: :quote_list
  get 'quote' => 'quote#create', as: :quote_create_api

  post 'order' => 'order#create', as: :order_create
  get 'order/:access_id'  => 'order#get', as: :order_details
  get 'orders' => 'order#list', as: :order_list

  get 'customers' => 'customer#list', as: :customer_list
  get 'customer/create' => 'customer#view_create', as: :customer_view_create
  post 'customer/create' => 'customer#change', as: :customer_create
  get 'customer/:access_id' => 'customer#details', as: :customer_details
  get 'customer/:customer_access_id/plants' => 'customer#plants', as: :customer_plants

  get 'customer/:customer_access_id/plant' => 'plant#view_create', as: :plant_view_create
  post 'customer/:customer_access_id/plant' => 'plant#create', as: :plant_create
  get 'customer/:customer_access_id/plant/:plant_id' => 'plant#details', as: :plant_details
  delete 'customer/:customer_access_id/plant/:plant_id' => 'plant#remove', as: :plant_remove

  get 'history' => 'history#list', as: :history
  get 'statistics' => 'ui#statistics', as: :statistic
  get 'bender' => 'ui#bender', as: :bender

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :customer_plants, :class_name => Plant
  has_many :quotes

  def serializable_hash
    super(:only => [:id])
  end

  def plants
    customer_plants.where(:active => true)
  end
end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController
  # :access_id
  def details
    @customer = Customer.find_by_access_id params[:access_id]

    error! 'Customer not found', :error_code => 404 if @customer.nil?

    respond_to do |f|
      f.html
      f.json { render :json => @customer.serializable_hash.merge(:plants => @customer.plants.map {|plant| {:id => plant.id, :url => plant_details_url(:customer_access_id => @customer.access_id, :plant_id => plant.id, :format => 'json')} })}
    end
  end

  def change
    if params.has_key? :id
      customer = Customer.find_by_id params[:id]
      error! 'Customer not found', :error_code => 404 if customer.nil?
    else
      customer = Customer.new
    end

    params.each do |key, value|
      next unless customer.has_attribute? key
      next if key == :id
      next if key == :access_id

      customer[key] = value
    end

    o = [('a'..'z'), ('A'..'Z'), (0..9)].map { |i| i.to_a }.flatten
    customer.access_id = (0...4).map{ o[rand(o.length)] }.join

    customer.save!
    HistoryEntry.create :message => "Customer ##{customer.id} created", :type => 'fa-users', :url => customer_details_path(:access_id => customer.access_id)

    redirect_to customer_details_path(:access_id => customer.access_id)
  end

  # :customer_access_id
  def plants
    @customer = Customer.find_by_access_id params[:customer_access_id]

    error! 'Customer not found', :error_code => 404 if @customer.nil?

    respond_to do |f|
      f.html
      f.json { render :json => @customer.plants.map {|plant| plant.serializable_hash } }
    end
  end

  def list
    @customers = Customer.all
    respond_to do |f|
      f.html
    end
  end

  def view_create
    respond_to do |f|
      f.html
    end
  end
end

app/views/customer/details.html.erb
<% content_for :title do %>Customer #<%=@customer.id%><% end %>
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Customer <a href="<%= plant_view_create_path(:customer_access_id => @customer.access_id) %>" class="btn pull-right btn-success"><span class="fa fa-plus"></span> Create Plant</a></h1>
  </div>
</div>
<div class="row">
  <div class="col-lg-6">
    <table class="table table-responsive">
      <tr>
        <td class="lead no-border">ID</td>
        <td class="no-border"><%=@customer.id%></td>
      </tr>
      <tr>
        <td class="lead no-border">Name</td>
        <td class="no-border"><%=@customer.name%></td>
      </tr>
      <tr>
    </table>
  </div>
</div>
<div class="row">
  <% @customer.plants.where(:active => true).each do |plant| %>
      <div class="col-lg-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            Plant <%= plant.id %>
          </div>
          <div class="panel-body">
            <table class="table table-responsive">
              <tr>
                <td>Address</td>
                <td><%= plant.address %></td>
              </tr>
              <tr>
                <td>Distance</td>
                <td><%= number_with_delimiter((plant.distance.to_f/1000).to_i, delimiter: '.', separator: ',') %> km</td>
              </tr>
            </table>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/customer/list.html.erb
<% content_for :title do %>Customers<% end %>
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Customers <a href="<%= customer_view_create_path %>" class="btn pull-right btn-success"><span class="fa fa-plus"></span> Create</a></h1>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <p>We have <strong><%=@customers.length %></strong> different customers.</p>
    <div class="table-responsive">
      <table class="table table-stripped table-hover sortable">
        <thead>
        <tr>
          <th>#</th>
          <th>Name <span class="fa fa-sort pull-right sort"></span></th>
          <th>Discount <span class="fa fa-sort pull-right sort"></span></th>
          <th>Plants </th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td><a href="<%= customer_details_path(:access_id => customer.access_id)%>"><strong><%= customer.name%></strong></a></td>
              <td><%= customer.discount%>%</td>
              <td><%= customer.plants.count%></td>
              <td>
                <a href="<%= customer_details_path(:access_id => customer.access_id)%>"><span class="fa fa-long-arrow-up"></span> View details</a>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/customer/view_create.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Create Customer</h1>
  </div>
</div>
<div class="row">
  <div class="col-lg-8">
    <form action="<%=customer_create_path%>" method="post">

      <!-- Table -->
      <table class="table">
        <tr>
          <td class="lead no-border">Name</td>
          <td class="no-border"><input type="text" class="form-control" name="name"></td>
        </tr>
        <tr>
          <td class="lead">Discount</td>
          <td><input type="text" class="form-control" name="discount"></td>
        </tr>
        <tr>
          <td></td>
          <td><input type="submit" class="btn btn-success" value="Submit"></td>
        </tr>

      </table>

    </form>
  </div>
</div>