config/routes.rb
SPO::Application.routes.draw do

  root 'ui#view_home'

  get 'materials' => 'material#list', as: :material_list
  get 'material/create' => 'material#view_create', as: :material_view_create
  post 'material/create' => 'material#change', as: :material_create
  get 'material/:material_id' => 'material#get', as: :material_details
  post 'material/:id' => 'material#change', as: :material_change
  get 'material/:material_id/delete' => 'material#remove', as: :material_remove

  get 'quote/create' => 'quote#view_create', as: :quote_view_create
  post 'quote/create' => 'quote#create', as: :quote_create
  get 'quote/:access_id' => 'quote#get', as: :quote_details
  get 'quote/:access_id/order' => 'order#view_create', as: :order_view_create
  get 'quotes' => 'quote#list', as: :quote_list
  get 'quote' => 'quote#create', as: :quote_create_api

  post 'order' => 'order#create', as: :order_create
  get 'order/:access_id'  => 'order#get', as: :order_details
  get 'orders' => 'order#list', as: :order_list

  get 'customers' => 'customer#list', as: :customer_list
  get 'customer/create' => 'customer#view_create', as: :customer_view_create
  post 'customer/create' => 'customer#change', as: :customer_create
  get 'customer/:access_id' => 'customer#details', as: :customer_details
  get 'customer/:customer_access_id/plants' => 'customer#plants', as: :customer_plants

  get 'customer/:customer_access_id/plant' => 'plant#view_create', as: :plant_view_create
  post 'customer/:customer_access_id/plant' => 'plant#create', as: :plant_create
  get 'customer/:customer_access_id/plant/:plant_id' => 'plant#details', as: :plant_details
  delete 'customer/:customer_access_id/plant/:plant_id' => 'plant#remove', as: :plant_remove

  get 'history' => 'history#list', as: :history
  get 'statistics' => 'ui#statistics', as: :statistic
  get 'bender' => 'ui#bender', as: :bender

end

app/views/layouts/application.html.erb
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title><%= yield :title%></title>

  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="Planet Express">
  <link href="<%= image_path 'icon.png' %>"  sizes="120x120"rel="apple-touch-icon">

  <!-- CSS -->
  <%= stylesheet_link_tag    "application", media: "all" %>

  <!-- Custom Fonts -->
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>

<body>
<div id="wrapper">

  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><span class="fa fa-rocket"></span> Planet Expres</a><a class="navbar-brand bender" href="<%=bender_path%>">s </a>
    </div>
    <!-- /.navbar-header -->
    <!-- /.navbar-top-links -->
    <div class="navbar-default sidebar" role="navigation">
      <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
          <li>
            <a <%#class="active"%> href="<%= root_path %>"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
          </li>
          <li>
            <a href="<%=material_list_path %>"><i class="fa fa-cubes fa-fw"></i> Material</a>
          </li>
          <li>
            <a href="<%= quote_list_path %>"><i class="fa fa-question-circle fa-fw"></i> Quotes</a>
          </li>
          <li>
            <a href="<%= order_list_path%>"><i class="fa fa-star fa-fw"></i> Orders</a>
          </li>
          <li>
            <a href="<%= customer_list_path%>"><i class="fa fa-users fa-fw"></i> Customers</a>
          </li>
          <li>
            <a href="<%= statistic_path%>"><i class="fa fa-bar-chart-o fa-fw"></i> Statistics</a>
          </li>
          <li>
            <a href="<%= history_path%>"><i class="fa fa-clock-o fa-fw"></i> History</a>
          </li>
        </ul>
      </div>
      <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
  </nav>
  <div id="page-wrapper"><%= yield %></div>
</div>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<%= javascript_include_tag "application" %>
<%= yield :foot%>
</body>
</html>